name: spend_monitor
version: "1.0.0"
config-version: 2
profile: spend_monitor

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  spend_monitor:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
